# Generated by Django 6.0.4 on 2026-04-16 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospital", "0001_initial"),
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsenceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("impacts_quota", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("max_hours", "Heures max"),
                            ("rest_time", "Temps de repos"),
                            ("min_staff", "Effectif minimum"),
                            ("max_shifts", "Gardes maximum"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=20)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShiftType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("duration_hours", models.IntegerField()),
                ("requires_rest_after", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("expected_end_date", models.DateField()),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                ("is_planned", models.BooleanField(default=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="personnel.staff",
                    ),
                ),
                (
                    "absence_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="planning.absencetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("min_staff", models.IntegerField(default=1)),
                ("max_staff", models.IntegerField(default=5)),
                (
                    "care_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="hospital.careunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShiftRequiredCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personnel.certification",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="planning.shift"
                    ),
                ),
            ],
            options={
                "unique_together": {("shift", "certification")},
            },
        ),
        migrations.AddField(
            model_name="shift",
            name="required_certifications",
            field=models.ManyToManyField(
                blank=True,
                through="planning.ShiftRequiredCertification",
                to="personnel.certification",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="shift_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="planning.shifttype"
            ),
        ),
        migrations.CreateModel(
            name="PatientLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("patient_count", models.IntegerField()),
                ("occupancy_rate", models.FloatField()),
                (
                    "care_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_loads",
                        to="hospital.careunit",
                    ),
                ),
            ],
            options={
                "unique_together": {("care_unit", "date")},
            },
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="planning.shift",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_assignments",
                        to="personnel.staff",
                    ),
                ),
            ],
            options={
                "unique_together": {("shift", "staff")},
            },
        ),
    ]
