# Generated by Django 6.0.4 on 2026-04-16 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospital", "0001_initial"),
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_services",
                to="personnel.staff",
            ),
        ),
        migrations.AddField(
            model_name="careunit",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="care_units",
                to="hospital.service",
            ),
        ),
        migrations.AddField(
            model_name="servicestatus",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="hospital.service",
            ),
        ),
        migrations.AddField(
            model_name="staffserviceassignment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hospital.service"
            ),
        ),
        migrations.AddField(
            model_name="staffserviceassignment",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="personnel.staff"
            ),
        ),
    ]
